name: modulex
description: ModuleX

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.9.4

  # barcode: ^2.2.4
  flutter_qr_bar_scanner: ^3.0.2 #QR/barcod
  wakelock: ^0.6.2  #화면 안꺼짐
  flutter_vibrate: ^1.3.0 #진동
  flutter_beep: ^1.0.0 #소리

  #아이콘
  flutter_launcher_icons: ^0.13.1 #아이콘
  #데이터 관리 firebase
  firebase_core: ^2.7.0
  firebase_database: ^10.0.15



dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter





flutter:


  uses-material-design: true

  assets:
    - Image/
